import localFont from "next/font/local";
import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";

// context
import NavContextProvider from "@/context/NavContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const vazirFont = localFont({
  src: "../../public/assets/vazirmatn-v33.003/fonts/ttf/Vazirmatn-Regular.ttf",
});

export default function RootLayout({ children }) {
  return (
    <NavContextProvider>
      <html lang="en">
        <body className={`overflow-x-hidden relative${vazirFont.className}`}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </NavContextProvider>
  );
}
